main: ovh.tgrhavoc.mvpgadgets.MVPGadgets
name: MVPGadgets
version: 1.4.0
softdepend: [Vault]
authors: [pookeythekid, TGRHavoc, JoshMullins, 97WaterPolom, TheFreakLord, AdamQpzm]

commands:
  mvpgadgets:
    aliases: [mvp, mvpg]
    description: The main commmand for MVPGadgets!
  gadget:
    description: Open the Gadget GUI.
  mobcannon:
    aliases: [mbc]
    description: Help menu for the Mob Cannon commands.
  mobcannonreload:
    aliases: [mobcannonrl, mcreload, mcrl, reloadmobcannon]
    description: Reload Mob Cannon.
  launchmob:
    aliases: [launch,lmob,lm]
    description: Launch a mob.
  moblist:
    aliases: [listmobs, launcherlist, launchlist]
    description: List all available mobs.
  mobnames:
    aliases: [altmobnames, altmobs]
    description: Get alternate names for a mob.
